#!/usr/bin/python
# -*- coding: utf8 -*-

# Imports:

import os, string, argparse, subprocess, distutils.spawn, sys, shutil, random, sys, time, re

# Constants:

VERSION = 'v5.15.3'
SELF_PATH = '/mnt/xtra/ark/bin/video-optimizer'
VXT = ['mkv', 'mp4', 'm4v', 'mov', 'mpg', 'mpeg', 'avi', 'vob', 'mts', 'm2ts', 'wmv', 'flv', 'webm']
TEST_TIME = 300
CODEC_PRESET_X264 = 'faster'
CODEC_PRESET_X265 = 'faster'
VIDEO_QUALITY_X264 = 22
VIDEO_QUALITY_X264_LQ = 22
VIDEO_QUALITY_X265 = -1
CODEC_AUDIO_BITRATE_AAC = 128
CODEC_AUDIO_BITRATE_AC3 = 192
CODEC_AUDIO_BITRATE_OPUS = 128
CODEC_AUDIO_BITRATE_VORBIS = 128
SPANISH = 'Spanish'
ENGLISH = 'English'
JAPANESE = 'Japanese'
LATIN = 'Latin'
THUMB_POOL_SIZE = 3
#FONT_NAME = 'Arial'
FONT_NAME = 'Trebuchet MS'
FONT_BOLD = '0'
FONT_SIZE = '96'

if os.name == 'posix':
  FFMPEG_BIN = 'ffmpeg'
  HANDBRAKECLI_BIN = 'HandBrakeCLI'
  MEDIAINFO_BIN = 'mediainfo'
  MKVPROPEDIT_BIN = 'mkvpropedit'
  NICE_BIN = 'nice'
else:
  BIN_PATH = 'C:/script/bin/'
  FFMPEG_BIN = '%sffmpeg.exe'%(BIN_PATH)
  HANDBRAKECLI_BIN = '%sHandBrakeCLI.exe'%(BIN_PATH)
  MEDIAINFO_BIN = '%sMediaInfo.exe'%(BIN_PATH)
  MKVPROPEDIT_BIN = '%smkvpropedit.exe'%(BIN_PATH)
  NICE_BIN = ''

# Options:

parser = argparse.ArgumentParser(description = 'Video transcoder/processor (%s)'%(VERSION))
parser.add_argument('-a', nargs = 1, help = 'Audio track -first track is 0- (language chosen by default)')
parser.add_argument('-c', action = 'store_true', help = 'Cartoon mode (CODEC specific tune for cartoon movies)')
parser.add_argument('-d', action = 'store_true', help = 'Deinterlace video')
parser.add_argument('-j', action = 'store_true', help = 'Japanese Anime mode')
parser.add_argument('-jss', action = 'store_true', help = 'Japanese Anime mode (SoftSub)')
parser.add_argument('-k', action = 'store_true', help = 'Matroska (MKV) output')
parser.add_argument('-l', action = 'store_true', help = 'Low resolution (720p)')
parser.add_argument('-lp', action = 'store_true', help = 'Low resolution portrait (1280p)')
parser.add_argument('-lq', action = 'store_true', help = 'Low resolution quarter (540p)')
parser.add_argument('-o', nargs = 1, help = 'Output path')
parser.add_argument('-q', nargs = 1, help = 'Quantizer factor')
parser.add_argument('-r', action = 'store_true', help = 'Rebuild original folder structure')
parser.add_argument('-s', nargs = 1, help = 'Subtitle track -first track is 0- (spanish forced searched by default)')
parser.add_argument('-t', action = 'store_true', help = 'Test mode (only the first %d s of video are processed)'%(TEST_TIME))
parser.add_argument('-v', action = 'store_true', help = 'Verbose mode')
parser.add_argument('-w', action = 'store_true', help = 'Overwrite existing files (skip by default)')
parser.add_argument('-x', action = 'store_true', help = 'X265 codec')
parser.add_argument('-z', action = 'store_true', help = 'dry run')
parser.add_argument('--abr', nargs = 1, help = 'Audio bit rate')
parser.add_argument('--ac3', action = 'store_true', help = 'AC3 audio')
parser.add_argument('--iphone', action = 'store_true', help = 'iPhone resolution (640p)')
parser.add_argument('--ipadmini', action = 'store_true', help = 'iPad mini resolution (576p)')
parser.add_argument('--minitest', action = 'store_true', help = 'Mini test mode (only 10 seconds are processed)')
parser.add_argument('--mono', action = 'store_true', help = 'Mono audio')
parser.add_argument('--mp3', action = 'store_true', help = 'MP3 audio')
parser.add_argument('--nonice', action = 'store_true', help = 'No nice for transcoding')
parser.add_argument('--galaxy', action = 'store_true', help = 'Samsung Galaxy resolution (480p)')
parser.add_argument('--opus', action = 'store_true', help = 'Opus audio')
parser.add_argument('--rotate90', action = 'store_true', help = 'Rotate clockwise 90 degrees')
parser.add_argument('--rotate270', action = 'store_true', help = 'Rotate clockwise 270 degrees')
parser.add_argument('--tag', nargs = 1, help = 'Tag instead autogenerated ones')
parser.add_argument('--upload', action = 'store_true', help = 'Upload script to GITHUB [BETA]')
parser.add_argument('--vorbis', action = 'store_true', help = 'Vorbis audio')
parser.add_argument('input', nargs='*', help = 'input file(s) (if missing process all video files)')
args = parser.parse_args()

FFMPEG_TEST_OPTS = ''
FFMPEG_OVERWRITE_OPTS = ''
HANDBRAKE_TEST_OPTS = ''
if args.t:
  FFMPEG_TEST_OPTS = ' -t %d '%(TEST_TIME)
  HANDBRAKE_TEST_OPTS = ' --stop-at duration:%s '%(TEST_TIME)
else:
  if args.minitest:
    FFMPEG_TEST_OPTS = ' -ss 00:02:00 -t 10 '
    HANDBRAKE_TEST_OPTS = ' --start-at duration:120 --stop-at duration:10 '
if args.w:
  FFMPEG_OVERWRITE_OPTS = ' -y '

# Auxiliar functions:

def empieza(a, b):
  return a[0:len(b)].lower() == b.lower()

def print_message(s, i):
  if i > 0 or args.v:
    print s

def remove_brackets(s):
  ss = s
  b = 0
  for i in range(0, len(s)):
    if s[i] == '[':
      b = 1
      x = i
    if b == 1 and s[i] == ']':
      ss = remove_brackets(s[:x] + s[i + 1:])
      break
  return ss

def language_code(name):
  if name == SPANISH:
    return 'spa'
  else:
    if name == ENGLISH:
      return 'eng'
    else:
      if name == JAPANESE:
        return 'jpn'
      else:
        if name == LATIN:
          return 'lat'
        else:
          return 'unk'

def boolean2integer(b):
  if b:
    return 1
  else:
    return 0
    
def analiza_estilos():
  f = open('temp1.ass', 'r')
  estilos = []
  apariciones = []
  tamano_font = []
  cursiva = []
  while True:
    l = f.readline()
    if not l:
      break
    if empieza(l, 'Dialogue:') or empieza(l, 'Comment:'):
      x = l.split(',')
      if not (x[3] in estilos):
        estilos.append(x[3])
        apariciones.append(0)
        tamano_font.append(0)
        cursiva.append(False)
      i = estilos.index(x[3])
      s = ''
      for j in range(9, len(x)):
        s = s + x[j]
      if x[3] == 'Signs':
        print '<<<<<%s>>>>>'%(s)
      s = re.sub('{[^}]+}', '', s)
      #s = re.sub('[ ]+', '', s)
      #s = re.sub('[\.]+', '', s)
      #s = re.sub('[\-]+', '', s)
      #s = re.sub('[0-9]+', '', s)
      s = re.sub(' [a-zA-Z] ', '', s)
      s = re.sub('^[a-zA-Z] ', '', s)
      #s = re.sub(' [A-Z] ', '', s)
      #s = re.sub('^[a-z] ', '', s)
      #s = re.sub('^[A-Z] ', '', s)
      #s = re.sub('[^a-z] ', '', s)
      #s = re.sub('[^A-Z] ', '', s)
      #s = re.sub('[ ]+', '', s)
      #s = re.sub('[\.]+', '', s)
      #s = re.sub('[\r]', '', s)
      s = re.sub('[^a-zA-Z]', '', s)
      if x[3] == 'Signs':
        print '<<<<<%s>>>>>'%(s)
      apariciones[i] = apariciones[i] + len(s)
  f.close()
  f = open('temp1.ass', 'r')
  while True:
    l = f.readline()
    if not l:
      break
    if empieza(l, 'Style:'):
      x = l.split(',')
      x0 = x[0].split(' ')
      s = x0[1]
      if s in estilos:
        i = estilos.index(s)
        tamano_font[i] = x[2]
        cursiva[i] = not(x[8] == '0')
  f.close()
  resumen = []
  for i in range(len(estilos)):
    resumen.append([apariciones[i], estilos[i], tamano_font[i], cursiva[i]])
  resumen.sort(reverse = True)
  return resumen

def encuentra_estilos_principal(resumen_estilos): # ***********************
  return resumen_estilos[0][1]

def encuentra_estilos_cursiva(resumen_estilos): # ***********************
  for i in range(1, len(resumen_estilos)):
    if resumen_estilos[i][3] and (resumen_estilos[i][2] == resumen_estilos[0][2]):
      return resumen_estilos[i][1]
  else:
    return ''

def cambia_formato(x, f, c, v):
  try:
    x[f.index(c.lower())] = v
  except:
    pass
  return x

# Classes:

class MediaInfo:

  def __init__(self):
    self.audio_codec = []
    self.audio_languages = []
    self.audio_channels = []
    self.audio_descriptions = []
    self.audio_default = []
    self.sub_languages = []
    self.sub_formats = []
    self.sub_forced = []

  def audio_tracks_count(self):
    return len(self.audio_languages)

  def sub_tracks_count(self):
    return len(self.sub_languages)

  def print_info(self):
    print_message('* Media info found:', 0)
    print_message('- Video width: %d (%dp)'%(self.video_width, self.video_resolution), 0)
    for t in range(0, self.audio_tracks_count()):
      print_message('- Audio track %d: Codec = %s, Language = %s, Channels = %d, Audio Description = %s, Default = %s'%(t, self.audio_codec[t], self.audio_languages[t], self.audio_channels[t], self.audio_descriptions[t], self.audio_default[t]), 0)
    for t in range(0, self.sub_tracks_count()):
      print_message('- Subtitle track %d: Language = %s, Format = %s, Forced = %s'%(t, self.sub_languages[t], self.sub_formats[t], self.sub_forced[t]), 0)

  def select_audio_track(self, l):
    print_message('* Searching for %s audio track...'%(l), 0)
    r = -1
    for i in range(0, self.audio_tracks_count()):
      if (not self.audio_descriptions[i]) and self.audio_languages[i] == l:
        if self.audio_channels[i] == 2:
          r = i
          break
    if r < 0:
      print_message('* Searching for %s audio track (2nd lap)...'%(l), 0)
      for i in range(0, self.audio_tracks_count()):
        if (not self.audio_descriptions[i]) and self.audio_languages[i] == l:
          r = i
          break
    print_message('- Audio track selected = %d'%(r), 0)
    return r

  def select_sub_track(self, l, f):
    print_message('* Searching for %s (Forced = %s) subtitle track...'%(l, f), 0)
    r = -1
    for i in range(0, self.sub_tracks_count()):
      if self.sub_languages[i] == l and not self.sub_formats[i] == 'PGS' and self.sub_forced[i] == f:
        r = i
        break
    print_message('- Subtitle track selected = %d'%(r), 0)
    return r

class MediaFile:

  def __init__(self, input_file):

    self.input_file = input_file

    # Extension extraction
    print_message('* Extracting file name path & extension...', 0)
    r = os.path.splitext(self.input_file)
    n = r[0]
    input_path = r[0].rsplit('/', 1)
    if len(input_path) > 1:
      self.input_path = input_path[0] + '/'
      self.base_input_filename = input_path[1]
    else:
      self.input_path = ''
      self.base_input_filename = input_path[0]
    self.extension = r[1].lower()
    self.extension = self.extension[1:]
    r2 = os.path.splitext(self.base_input_filename)
    pre_ext = r2[1].lower()
    pre_ext = pre_ext[1:]
    if pre_ext == '4k':
      self.base_input_filename = self.base_input_filename[0:-3]
    print_message('- Input path: "%s"'%(self.input_path), 0)
    print_message('- Base input file name: "%s"'%(self.base_input_filename), 0)
    print_message('- Extension: "%s"'%(self.extension), 0)

    # Output file calculation
    if args.o: # Output path
      d = args.o[0]
      if not d[-1] == '/':
        d += '/'
      self.output_path = d
    else:
      self.output_path = ''
    self.output_path += self.input_path
    print_message('- Output path: "%s"'%(self.output_path), 0)

    self.base_output_filename = remove_brackets(self.base_input_filename)
    self.base_output_filename = self.base_output_filename.lstrip()
    self.base_output_filename = self.base_output_filename.rstrip()
    self.base_output_filename = self.base_output_filename.replace('á', 'a')
    self.base_output_filename = self.base_output_filename.replace('é', 'e')
    self.base_output_filename = self.base_output_filename.replace('í', 'i')
    self.base_output_filename = self.base_output_filename.replace('ó', 'o')
    self.base_output_filename = self.base_output_filename.replace('ú', 'u')
    self.base_output_filename = self.base_output_filename.replace('ü', 'u')
    self.base_output_filename = self.base_output_filename.replace('ñ', 'n')
    self.base_output_filename = self.base_output_filename.replace('ç', 'c')
    self.base_output_filename = self.base_output_filename.replace('Á', 'A')
    self.base_output_filename = self.base_output_filename.replace('É', 'E')
    self.base_output_filename = self.base_output_filename.replace('Í', 'I')
    self.base_output_filename = self.base_output_filename.replace('Ó', 'O')
    self.base_output_filename = self.base_output_filename.replace('Ú', 'U')
    self.base_output_filename = self.base_output_filename.replace('Ü', 'U')
    self.base_output_filename = self.base_output_filename.replace('Ñ', 'N')
    self.base_output_filename = self.base_output_filename.replace('¿', '')
    self.base_output_filename = self.base_output_filename.replace('?', '')
    self.base_output_filename = self.base_output_filename.replace('¡', '')
    self.base_output_filename = self.base_output_filename.replace('!', '')

    if args.tag:
      filename_info = args.tag[0]
    else:
      filename_info = ''
      if args.jss:
        filename_info += 'SoftSub '
      if args.x:
        filename_info += 'X265 '
      if args.q:
        filename_info += 'Q{} '.format(args.q[0])
      if args.l:
        filename_info += '720p '
      else:
        if args.lq:
          filename_info += '540p'
        else:
          if args.lp:
            filename_info += '1280p '
          else:
            if args.ipadmini:
              filename_info += '576p '
            else:
              if args.iphone:
                filename_info += '640p '
              else:
                if args.galaxy:
                  filename_info += '480p '
                else:
                  filename_info += '1080p '
      if args.ac3:
        filename_info += 'AC3 '
      if args.opus:
        filename_info += 'OPUS '
      if args.vorbis:
        filename_info += 'VORBIS '
      if args.mp3:
        filename_info += 'MP3 '
      if args.abr:
        filename_info += '{}K '.format(args.abr[0])

    if filename_info != '':
      self.base_output_filename += ' [%s]'%(filename_info.rstrip())

    if not args.o:
      self.output_file = self.output_path + self.base_output_filename
    else:
      self.output_file = self.output_path + self.base_output_filename
    self.output_file_mkv = self.output_file + '.mkv'
    self.output_file_mp4 = self.output_file + '.mp4'
    if args.k:
      self.output_file = self.output_file_mkv
    else:
      self.output_file = self.output_file_mp4

    print_message('- Output file name: "%s"'%(self.output_file), 0)

  def GetMediaInfo(self):

    # Movie name:
    tmp_movie_name = self.base_input_filename.split('[')
    tmp_movie_name = tmp_movie_name[0].rstrip()
    movnamyea = tmp_movie_name
    movnamyea = movnamyea.split('/')
    movnamyea = movnamyea[-1]
    movnamyea = movnamyea.split('\\')
    movnamyea = movnamyea[-1]
    movnam = movnamyea
    self.movie_name = movnam
    print_message('- Extracted title: "%s"'%(self.movie_name), 0)

    # Media info extraction
    self.info = MediaInfo()
    if self.extension == 'mkv' or self.extension == 'mp4' or self.extension == 'avi' or self.extension == 'wmv':
      print_message('> Extracting file media info...', 0)
      # Video width
      o = subprocess.check_output('%s --Inform="Video;%%Width%%" "%s"'%(MEDIAINFO_BIN, self.input_file), shell=True)
      o = o.rstrip()
      try:
        self.info.video_width = int(o)
      except:
        self.info.video_width = 0
      if self.info.video_width > 3000:
        self.info.video_resolution = 2160
      else:
        if self.info.video_width > 1500:
          self.info.video_resolution = 1080
        else:
          self.info.video_resolution = 720
      # Audio tracks count
      o = subprocess.check_output('%s --Inform="General;%%AudioCount%%" "%s"'%(MEDIAINFO_BIN, self.input_file), shell=True)
      o = o.rstrip()
      try:
        audcnt = int(o)
      except:
        audcnt = 0
      print_message('- Audio tracks found = %d'%(audcnt), 0)
      # Audio CODECs
      o = subprocess.check_output('%s --Inform="General;%%Audio_Format_List%%" "%s"'%(MEDIAINFO_BIN, self.input_file), shell=True)
      o = o.rstrip()
      o = o.split(' / ')
      for i in range(0, audcnt):
        self.info.audio_codec.append(o[i])
      # Audio Languages
      o = subprocess.check_output('%s --Inform="General;%%Audio_Language_List%%" "%s"'%(MEDIAINFO_BIN, self.input_file), shell=True)
      o = o.rstrip()
      o = o.split(' / ')
      for i in range(0, audcnt):
        if len(o) >= i + 1:
          if o[i] == '':
            o[i] = 'Unknown'
        else:
          o.append('Unknown')
        self.info.audio_languages.append(o[i])
      # Audio Channels
      o = subprocess.check_output('%s --Inform="Audio;%%Channel(s)%%" "%s"'%(MEDIAINFO_BIN, self.input_file), shell=True)
      for i in range(0, audcnt):
        try:
          channels_amount = int(o[0:1])
        except:
          channels_amount = 0
        self.info.audio_channels.append(channels_amount)
        if o[1:4] == ' / ':
          o = o[5:]
        else:
          o = o[1:]
      # Audiodescription
      o = subprocess.check_output('%s --Inform="Audio;%%Title%%***" "%s"'%(MEDIAINFO_BIN, self.input_file), shell=True)
      s = o.split('***')
      for t in range(0, len(s) - 1):
        if ('descri' in s[t].lower()) or ('comenta' in s[t].lower()) or ('comment' in s[t].lower()) or ('invidente' in s[t].lower()):
          self.info.audio_descriptions.append(True)
        else:
          self.info.audio_descriptions.append(False)
      # Audio default
      o = subprocess.check_output('%s --Inform="Audio;%%Default%%/" "%s"'%(MEDIAINFO_BIN, self.input_file), shell=True)
      o = o.rstrip()
      o = o.split('/')
      self.info.audio_default = []
      for i in range(0, len(o) - 1):
        if o[i] == 'Yes':
          self.info.audio_default.append(True)
        else:
          self.info.audio_default.append(False)
      # Subtitle tracks count
      o = subprocess.check_output('%s --Inform="General;%%TextCount%%" "%s"'%(MEDIAINFO_BIN, self.input_file), shell=True)
      o = o.rstrip()
      if o == '':
        subcnt = 0
      else:
        subcnt = int(o)
      print_message('- Subtitle tracks found = %d'%(subcnt), 0)
      if subcnt == 0:
        self.info.sub_languages = []
        self.info.sub_forced = []
      else:
        # Subtitle languages
        o = subprocess.check_output('%s --Inform="General;%%Text_Language_List%%" "%s"'%(MEDIAINFO_BIN, self.input_file), shell=True)
        o = o.rstrip()
        if o[-1] == '/':
          o = o + ' Unknown'
        o = o.split(' / ')
        self.info.sub_languages = o
        # Subtitle formats
        o = subprocess.check_output('%s --Inform="General;%%Text_Format_List%%" "%s"'%(MEDIAINFO_BIN, self.input_file), shell=True)
        o = o.rstrip()
        o = o.split(' / ')
        self.info.sub_formats = o
        # Subtitle forced (by "Forced" field)
        o = subprocess.check_output('%s --Inform="Text;%%Forced%%/" "%s"'%(MEDIAINFO_BIN, self.input_file), shell=True)
        o = o.rstrip()
        o = o.split('/')
        self.info.sub_forced = []
        for i in range(0, len(o) - 1):
          if o[i] == 'Yes':
            self.info.sub_forced.append(True)
          else:
            self.info.sub_forced.append(False)
        # Subtitle forced (by "Title" field)
        o = subprocess.check_output('%s --Inform="Text;%%Title%%#@#" "%s"'%(MEDIAINFO_BIN, self.input_file), shell=True)
        o = o.rstrip()
        o = o.split('#@#')
        for i in range(0, len(o) - 1):
          if ('forz' in o[i].lower()) or ('forc' in o[i].lower()):
            self.info.sub_forced[i] = True
      self.info.print_info()

  # MAIN TRANSCODING ROUTINE *****
  def transcode(self, input_file, aud_list, sub_list):
    print_message('* Transcoding media file "%s" to "%s"...'%(input_file, self.output_file), 1)

    ENC_OPTS = ''

    if args.x:
      codec_pre = CODEC_PRESET_X265
      quantizer = VIDEO_QUALITY_X265
    else:
      codec_pre = CODEC_PRESET_X264
      if args.l or args.lp or args.ipadmini or args.galaxy or args.iphone:
        quantizer = VIDEO_QUALITY_X264_LQ
      else:
        quantizer = VIDEO_QUALITY_X264

    if args.q:
      quantizer = int(args.q[0])

    if args.ac3:
      audio_br = CODEC_AUDIO_BITRATE_AC3
    else:
      if args.opus:
        audio_br = CODEC_AUDIO_BITRATE_OPUS
      else:
        if args.vorbis:
          audio_br = CODEC_AUDIO_BITRATE_VORBIS
        else:
          if args.mp3 and not args.abr:
            audio_br = -1
          else:
            audio_br = CODEC_AUDIO_BITRATE_AAC
    if args.abr:
      audio_br = int(args.abr[0])

    options = ''
    options += ' --loose-anamorphic --modulus 2 --crop 0:0:0:0'
    options += ' --encoder-preset {} --cfr'.format(codec_pre)

    if args.x:
      options += ' --encoder x265'
    else:
      options += ' --encoder x264 --encoder-profile high --encoder-level 4.1'

    if args.rotate90:
      options += ' --rotate=angle=90:hflip=0'
    if args.rotate270:
      options += ' --rotate=angle=270:hflip=0'

    if args.l or args.lp or args.lq:
      if args.l:
        options += ' --maxWidth 1280'
      else:
        if args.lp:
          options += ' --maxWidth 720'
        else:
          options += ' --maxWidth 960'
    else:
      if args.ipadmini:
        options += ' --maxWidth 1024'
      else:
        if args.galaxy:
          options += ' --maxWidth 800'
        else:
          if args.iphone:
            options += ' --maxWidth 1136'
          else:
            options += ' --width 1920'

    if args.x:
      if args.c:
        ENC_OPTS += 'psy-rd=0.4:aq-strength=0.4:deblock=1,1:bframes=6:'
    else:
      if args.c:
        options += ' --encoder-tune animation'
      else:
        options += ' --encoder-tune film'

    #if args.l:
    #  maxrate = 2000 * 0.90 - audio_br
    #  ENC_OPTS += 'vbv-maxrate={}:vbv-bufsize={}:'.format(int(maxrate), int(maxrate * 10))
    #else:
    #  if args.lq:
    #    maxrate = 1000 * 0.90 - audio_br
    #    ENC_OPTS += 'vbv-maxrate={}:vbv-bufsize={}:'.format(int(maxrate), int(maxrate * 10))
    #  else:
    #    maxrate = 8000 * 0.90 - audio_br
    #    ENC_OPTS += 'vbv-maxrate={}:vbv-bufsize={}:'.format(int(maxrate), int(maxrate * 10))
    maxrate = 8000
    ENC_OPTS += 'vbv-maxrate={}:vbv-bufsize={}:'.format(int(maxrate), int(maxrate * 2))

    if not ENC_OPTS == '':
      options += '  --encopts {}'.format(ENC_OPTS[:-1])

    if quantizer >= 0:
      options += ' --quality {}'.format(quantizer)

    if args.d:
      options += ' --deinterlace'

    if args.mono:
      audopts = ' --mixdown mono'
    else:
      audopts = ' --mixdown stereo'
    if args.ac3:
      audopts += ' --aencoder ac3'
    if args.opus:
      audopts += ' --aencoder opus'
    if args.vorbis:
      audopts += ' --aencoder vorbis'
    if args.mp3:
      audopts += ' --aencoder mp3'
    if audio_br >= 0:
      audopts += ' --ab {}'.format(audio_br)
    else:
      if args.mp3:
        audopts += ' --aq 0'
    if len(aud_list) > 0:
      audopts += ' --audio '
      for n in range(0, len(aud_list)):
        audopts += '%d,'%(aud_list[n] + 1)
      audopts = audopts[:-1]

    subopts = ''
    if len(sub_list) > 0:
      subopts += ' --subtitle '
      for n in range(0, len(sub_list)):
        subopts += '%d,'%(sub_list[n] + 1)
      subopts = subopts[:-1]
    if sub_list:
      if self.info.sub_forced[sub_list[0]]:
        subopts += ' --subtitle-burned'

    # Subtitle processing:
    if args.j or args.jss:
      try:
        os.remove('temp1.ass')
        os.remove('temp2.ass')
        os.remove('temp.mkv')
      except:
        pass
      c = '{} {} -y -i "{}" -map 0:s:{} -vn -an -c:s copy temp1.ass'.format(FFMPEG_BIN, FFMPEG_TEST_OPTS, input_file, sub_list[0])
      execute_command(c, True)
      #h = 'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n'
      #a = 'Style: Gen_Main,Trebuchet MS,%s,&H00FFFFFF,&H00FFFF00,&H00000000,&H00222222,0,0,0,0,100,100,0,0,1,10,2,2,0,0,100,0018\n'%(FONT_SIZE)
      #b = 'Style: Gen_Ital,Trebuchet MS,%s,&H00FFFFFF,&H00FFFF00,&H00000000,&H00222222,0,1,0,0,100,100,0,0,1,10,2,2,0,0,100,0018\n'%(FONT_SIZE)
      #a = 'Style: Gen_Main,%s,%s,&H00FFFFFF,&H00FFFF00,&H00000000,&H00222222,%s,0,0,0,100,100,0,0,1,10,2,2,20,10,100,0018\n'%(FONT_NAME, FONT_SIZE, FONT_BOLD)
      #b = 'Style: Gen_Ital,%s,%s,&H00FFFFFF,&H00FFFF00,&H00000000,&H00222222,%s,1,0,0,100,100,0,0,1,10,2,2,20,10,100,0018\n'%(FONT_NAME, FONT_SIZE, FONT_BOLD)
      #resumen_estilos = analiza_estilos()
      #est_pri = encuentra_estilos_principal(resumen_estilos)
      #est_cur = encuentra_estilos_cursiva(resumen_estilos)
      f = open('temp1.ass', 'r')
      g = open('temp2.ass', 'w')
      en_styles = 0
      while True:
        l = f.readline()
        if not l:
          break
        if empieza(l, 'ScaledBorderAndShadow:'):
          g.write('ScaledBorderAndShadow: yes\n')
          continue
        if empieza(l, 'PlayResX:'):
          g.write('PlayResX: 1920\n')
          continue
        if empieza(l, 'PlayResY:'):
          g.write('PlayResY: 1080\n')
          continue
        if empieza(l, '[V4 Styles]'):
          en_styles = 1
          g.write(l)
          continue
        if empieza(l, '[V4+ Styles]'):
          en_styles = 2
          g.write(l)
          continue
        if en_styles >= 1 and en_styles <= 2 and empieza(l, 'Format:'):
          en_styles = en_styles * 10
          x = l
          x = x.lower()
          x = x.split(',')
          x[0] = x[0].split(':')[1]
          for n in range(len(x)):
            x[n] = x[n].lstrip()
            x[n] = x[n].rstrip()
          formato = x
          g.write(l)
          continue
        if empieza(l, 'Style:'):
          if args.v:
            print 'Style substitution: %s ===>'%(l)
          x = l.split(',')
          x = cambia_formato(x, formato, 'Fontname', FONT_NAME)
          x = cambia_formato(x, formato, 'Fontsize', FONT_SIZE)
          x = cambia_formato(x, formato, 'PrimaryColour', '&H00FFFFFF')
          x = cambia_formato(x, formato, 'SecondaryColour', '&H00FFFF00')
          x = cambia_formato(x, formato, 'BackColour', '&H00222222')
          x = cambia_formato(x, formato, 'Bold', FONT_BOLD)
          x = cambia_formato(x, formato, 'BorderStyle', '1') # Con borde
          x = cambia_formato(x, formato, 'Outline', '10') # Ancho del borde en pixeles
          x = cambia_formato(x, formato, 'Shadow', '2')
          x = cambia_formato(x, formato, 'Alignment', '2')
          x = cambia_formato(x, formato, 'MarginL', '0')
          x = cambia_formato(x, formato, 'MarginR', '0')
          x = cambia_formato(x, formato, 'MarginV', '100')
          x = cambia_formato(x, formato, 'AlphaLevel', '0')
          if en_styles == 10: # V4 Styles
            x = cambia_formato(x, formato, 'TertiaryColour', '&H00000000')
          else: # V4+ Styles
            x = cambia_formato(x, formato, 'OutlineColour', '&H00000000')
            x = cambia_formato(x, formato, 'Underline', '0')
            x = cambia_formato(x, formato, 'StrikeOut', '0')
            x = cambia_formato(x, formato, 'ScaleX', '100')
            x = cambia_formato(x, formato, 'ScaleY', '100')
            x = cambia_formato(x, formato, 'Spacing', '0')
          l = ','.join(x)
          if args.v:
            print l
          g.write(l)
          continue
        g.write(l)
      f.close()
      g.close()
      c = '{} {} -y -i "{}" -i temp2.ass -c:v copy -c:a copy -c:s copy -map 0:v -map 0:a -map 1:s:0 temp.mkv'.format(FFMPEG_BIN, FFMPEG_TEST_OPTS, input_file)
      execute_command(c, True)
      c = '{} "temp.mkv" --edit track:s1 --set language=spa --set flag-forced=1'.format(MKVPROPEDIT_BIN)
      execute_command(c, True)
      input_file = 'temp.mkv'
      subopts = ' --subtitle 1 --subtitle-burned'
      if args.v:
        print 'Subtitle format: '
        print formato
      #if args.v:
      #  print 'Styles founded:'
      #  for r in resumen_estilos:
      #    print r
      #  print 'Main style:    "%s"'%(est_pri)
      #  print 'Italic style:  "%s"'%(est_cur)
      #  wait_counter = 10
      #  while wait_counter > 0:
      #    sys.stdout.write('\r* Starting muxing in %02d s...'%(wait_counter))
      #    sys.stdout.flush()
      #    time.sleep(1)
      #    wait_counter -= 1
      #  print ''
    # Transcoding:
    if args.jss:
      c = 'mv "%s" "%s"'%(input_file, self.output_file)
    else:
      c = '%s %s -i "%s" --optimize --markers %s%s%s -o "%s"'%(HANDBRAKECLI_BIN, HANDBRAKE_TEST_OPTS, input_file, options, audopts, subopts, self.output_file)
    execute_command(c)
    if args.j or args.jss:
      try:
        os.remove('temp1.ass')
        os.remove('temp2.ass')
        os.remove('temp.mkv')
      except:
        pass

  def tag(self, aud_list, sub_list, output_file):
    if self.extension == 'mkv':
      movnamyea = self.movie_name
      movnamyea = movnamyea.split('/')
      movnamyea = movnamyea[-1]
      movnamyea = movnamyea.split('\\')
      movnamyea = movnamyea[-1]
      movnam = movnamyea
      c = '%s "%s" --edit info --set title="%s"'%(MKVPROPEDIT_BIN, output_file, movnam)
      execute_command(c)
      # Audio tracks
      for n in range(0, len(aud_list)):
        name = self.info.audio_languages[aud_list[n]]
        code = language_code(name)
        defa = boolean2integer(n == 0)
        forc = boolean2integer(n == 0)
        if forc == 1:
          name += ' Forced'
        if defa == 1:
          name += ' Default'
        c = '%s "%s" --edit track:a%d --set name="%s"'%(MKVPROPEDIT_BIN, output_file, n + 1, name)
        execute_command(c)
        c = '%s "%s" --edit track:a%d --set language=%s'%(MKVPROPEDIT_BIN, output_file, n + 1, code)
        execute_command(c)
        c = '%s "%s" --edit track:a%d --set flag-default=%d'%(MKVPROPEDIT_BIN, output_file, n + 1, defa)
        execute_command(c)
        c = '%s "%s" --edit track:a%d --set flag-forced=%d'%(MKVPROPEDIT_BIN, output_file, n + 1, forc)
        execute_command(c)
      # Subtitle tracks
      for n in range(0, len(sub_list)):
        name = self.info.sub_languages[sub_list[n]]
        code = language_code(name)
        defa = boolean2integer(n == 0)
        forc = boolean2integer(self.info.sub_forced[sub_list[n]])
        if forc == 1:
          name += ' Forced'
        if defa == 1:
          name += ' Default'
        c = '%s "%s" --edit track:s%d --set name="%s"'%(MKVPROPEDIT_BIN, output_file, n + 1, name)
        execute_command(c)
        c = '%s "%s" --edit track:s%d --set language=%s'%(MKVPROPEDIT_BIN, output_file, n + 1, code)
        execute_command(c)
        c = '%s "%s" --edit track:s%d --set flag-default=%d'%(MKVPROPEDIT_BIN, output_file, n + 1, defa)
        execute_command(c)
        c = '%s "%s" --edit track:s%d --set flag-forced=%d'%(MKVPROPEDIT_BIN, output_file, n + 1, forc)
        execute_command(c)

# Subroutines:

def execute_command(c, forced = False):
  if NICE_BIN != '' and not args.nonice:
    c = NICE_BIN + ' -n 19 ' + c
  print_message('> Executing: %s'%(c), 0)
  if not args.z or forced:
    os.system(c)

def transcode_video_file(f):

  v = MediaFile(f)

  if v.extension in VXT:
    #if not args.w and os.path.isfile(v.output_file):
    #  print '* Destination file already exists (skipping)'
    #  return
    if not args.w and (os.path.isfile(v.output_file_mp4) or os.path.isfile(v.output_file_mkv)):
      print_message('* Destination file already exists (skipping)', 0)
      return
  else:
    print_message('* ERROR: input file is not a video file (skipping)', 1)
    return

  v.GetMediaInfo()

  # Audio/sub tracks processing:

  track_audio_spa = v.info.select_audio_track(SPANISH)
  track_audio_lat = v.info.select_audio_track(LATIN)
  track_audio_eng = v.info.select_audio_track(ENGLISH)
  track_audio_jpn = v.info.select_audio_track(JAPANESE)
  track_sub_spa   = v.info.select_sub_track(SPANISH, False)
  track_sub_spa_f = v.info.select_sub_track(SPANISH, True)
  track_sub_lat_f = v.info.select_sub_track(LATIN, True)

  track_audio = 0
  if track_audio_jpn >= 0: # Japanese audio
    track_audio = track_audio_jpn
  if track_audio_eng >= 0: # English audio
    track_audio = track_audio_eng
  if track_audio_lat >= 0: # Latin audio
    track_audio = track_audio_lat
  if track_audio_spa >= 0: # Spanish audio
    track_audio = track_audio_spa
  if args.a: # Audio track selected by user
    track_audio = int(args.a[0])
  aud_list = [track_audio]

  sub_list = []
  if track_sub_spa_f >= 0:
    sub_list.append(track_sub_spa_f)
  else:
    if track_audio_spa < 0 and track_sub_lat_f >= 0:
      sub_list.append(track_sub_lat_f)

  print ''
  print '<<<<<<<<<< TRANSCODING PLANNING >>>>>>>>>>'
  print ' - Input file: "%s"'%(v.input_file)
  print ' - Output file: "%s"'%(v.output_file)
  if args.l:
    print ' - Video resolution: 720p'
  else:
    if args.ipadmini:
      print ' - Video resolution: 576p'
    else:
      if args.galaxy:
        print ' - Video resolution: 480p'
      else:
        if args.iphone:
          print ' - Video resolution: 640p'
        else:
          if args.lq:
            print ' - Video resolution: 540p'
          else:
            print ' - Video resolution: 1080p'
  if v.info.audio_languages:
    print ' - Audio language: %s'%(v.info.audio_languages[aud_list[0]])
  if not sub_list:
    print ' - Subtitle language: no suitable subtitles found'
  else:
    print ' - Subtitle language: {} (BURNED = {})'.format(v.info.sub_languages[sub_list[0]], v.info.sub_forced[sub_list[0]])
  print '<<<<<<<<<< -------------------- >>>>>>>>>>'
  print ''

  if not args.z:
    wait_counter = 5
    while wait_counter > 0:
      sys.stdout.write('\r* Starting transcoding in %02d s...'%(wait_counter))
      sys.stdout.flush()
      time.sleep(1)
      wait_counter -= 1
    print ''
  v.transcode(f, aud_list, sub_list)

  if args.k: # Post-tagging if MKV output:
    v.tag(aud_list, [], v.output_file)

def process_file(f):
  transcode_video_file(f)

def process_directory(dir):
  lis = os.listdir(dir)
  lis.sort()
  for arc in lis:
    rut = dir + '/' + arc
    if os.path.isdir(rut):
      if args.o:
        nueva_ruta = rut
        if nueva_ruta[0] == '.':
          nueva_ruta = nueva_ruta[1:]
        nueva_ruta = args.o[0] + nueva_ruta
        if args.r and not os.path.exists(nueva_ruta):
          print_message("Creating directory: %s"%(nueva_ruta), 0)
          if not args.z:
            os.makedirs(nueva_ruta)
      process_directory(rut)
    else:
      process_file(rut)

def verify_software(b, critical):
  s = 'Checking for "%s"...'%(b)
  if not b == '':
    if distutils.spawn.find_executable(b) is None:
      if critical:
        s += 'MISSING!'
        print_message(s, 2)
        sys.exit()
      else:
        s += 'MISSING! (WARNING)'
        print_message(s, 0)
    else:
      s += 'OK'
      print_message(s, 0)

# Main routine:

verify_software(HANDBRAKECLI_BIN, True)
verify_software(MEDIAINFO_BIN, True)
verify_software(MKVPROPEDIT_BIN, True)
verify_software(NICE_BIN, True)

if args.upload:
  try:
    os.chdir(SELF_PATH)
  except:
    print_message('Error changing to source directory.', 1)
  c = 'git commit -a -m "%s" ; git push'%(VERSION)
  execute_command(c)
else:
  if args.input:
    for f in args.input:
      process_file(f)
  else:
    process_directory('.')
